### ISSUE TITLE
[Bug]: path to mQTL mapping

### ISSUE THREAD

**Issue by epzjlm** [genetics-of-dna-methylation-consortium/godmc_phase2#24]
### Scripts

04e-single-site-analysis.sh

### What happened?

04e-single-site-analysis.sh
	Modified the following as:
        -mapper ${home_directory}/results/04/mapping/ to -mapper ${hase_mapping}

### R version

4.4.0 (April, 2024)

### Python version

None

**Comment by ejh243** [comment]
I don't know enough about Hase to validate this change is correct but happy to implement if others are confident?

**Comment by ZXiaopu** [comment]
I made this change on my end but got errors "ValueError: There is no flip mapper data in folder ${hase_mapping}".

Additional parameter changes may be needed in other 04 scripts. 

I can look into this issue and run 04 if necessary.

**Comment by ZXiaopu** [comment]
The mapper path has been updated in 04e.

No more modification was needed. The previous error was because of my outdated results from 04d. I reran the04a-04e and all work well. A pull request has been made. https://github.com/genetics-of-dna-methylation-consortium/godmc_phase2/pull/33#issue-2542725606
